### ISSUE TITLE
Can't use rmarkdown::render with ggplot2 graph

### ISSUE THREAD

**Issue by RossElmes** [INWTlab/ireports#12]
I am having an issue with the report when I try run it using rmarkdown::render it is giving the following error.  

![Screen Shot 2019-03-13 at 16 16 21](https://user-images.githubusercontent.com/18209403/54295721-85525380-45ab-11e9-9f40-6cdf2cc86a57.png)

This problem only arrises when I included a ggplot2 graph which I want to use for visualisation.

The file knits perfectly when I click "knit" from rmarkdown document with the ggplot 2 graph

**Comment by SarahWagner** [comment]
@RossElmes I'm having no troubles to render the document including a ggplot2 graph via `rmarkdown::render()`. Would you please provide me a minimal example that produces the error and the exact command you're using to render the document?

**Comment by RossElmes** [comment]
@SarahWagner thanks for the response.  The only difference in the markdown file is that I added the below chunk 

```{r Example Plot}

iris%>%
  ggplot(.,aes(x = Sepal.Length,y = Sepal.Width))+
  geom_point()

```
I am calling this function from another script

```{r}
rmarkdown::render('Desktop/Example for INWTLAB/Example 01/Example 01.Rmd',
                  output_dir = 'Desktop/Example for INWTLAB/Example 01')
```


Error is below

![Screen Shot 2019-03-15 at 12 20 57](https://user-images.githubusercontent.com/18209403/54430920-e3eb0f00-471c-11e9-9e01-f5f55ea913ba.png)


Session Info is below 

![Screen Shot 2019-03-15 at 12 19 53](https://user-images.githubusercontent.com/18209403/54430934-ebaab380-471c-11e9-8ea6-75c3564b21b9.png)

Any help is greatly appreciated.
R

**Comment by SarahWagner** [comment]
@RossElmes Could you please set the `keep_tex` option to `true` in the yaml header of the script from within you're calling the `rmarkdown::render()` function:

```
pdf_document:
    keep_tex: true
```
Since it is a latex problem, you may see what the actual problem is if you take a look at the resulting tex file after rendering the main document again. If not, please provide me with the tex file, a minimal example of your main script and also the script that is being rendered within it.
