### ISSUE TITLE
Custom layout items

### ISSUE THREAD

**Issue by tom-parkinson** [INWTlab/ireports#13]
Hi, thanks so much for the template. It works perfectly. I'm comfortable in R but new to latex so I have some questions about how best to modify default layout items:
- tweak ToC so no subheadings are shown
- change size and color of headings throughout document
- remove paragraph indentations
- add author field to page footer

Sorry if this isn't the right place - I didn't know where else to contact you.
Thanks!

**Comment by SarahWagner** [comment]
@tom-parkinson Thanks, glad to hear the template is of good use to you. 

In order to change the color of the headers, which are colored using `iblue`, change the hexadecimal color value for `iblue` in the yaml header. 

To add the author it should be sufficient to type the name for example into `\lfoot{}` (file defs.tex) in section "header and footer".

For disabling indentation the latex command `\setlength\parindent{0pt}` can be used, see https://tex.stackexchange.com/questions/14375/how-to-disable-automatic-indentation-on-new-paragraphs

And the toc should not list subsections if you set the toc depth via `\setcounter{tocdepth}{1}`, before `\tableofcontents` is called, also see https://alvinalexander.com/blog/post/linux-unix/latex-setting-table-of-contents-toc-depth
