### ISSUE TITLE
Links in IReports

### ISSUE THREAD

**Issue by w2felix** [INWTlab/ireports#15]
Hi,
when I try to add links into a RMarkdown file using the IReports package by using the RMarkdown code:
`[link](www.google.com)`

I get following error, when knitting the report:

> ! Undefined control sequence.
> l.45 \href
>          {www.google.com}{link} 
>
> ! xelatex.exe: Windows API error 5: Zugriff verweigert

could you help me?
Best
Felix

**Comment by amitghosh-inwt** [comment]
Given the output, it's not straightforward to identify the root cause of the problem. The `[link](www.google.com)` is translated to `\href{www.google.com}{link}` in Tex, which is not recognized. It would require a package like `hyperref` to be included. But then there is the "Windows API" error. This could have various reasons. Can you provide a small example, so that we can try to reproduce the problem?
