### ISSUE TITLE
report a bug

### ISSUE THREAD

**Issue by stewartli** [INWTlab/ireports#4]
Thank you very much for making such a nice and neat RMD template. 
I feel there is a bug. Your firm logo gets generated every time after I  render the document. 
Any advice. Cheers.

**Comment by SarahWagner** [comment]
@stewartli Thank you very much for reporting. 
Your logo has been replaced by the default logo from the skeleton folder everytime you compiled the document. While this is a useful feature for our own reports, because we can make central changes in the skeleton and these are automatically applied to all our reports without having to change each report by hand, it is of course undesired in this case. I fixed this behaviour by adding the argument `resetStyleFiles` to the function `IReports::businessReport()`. This is now per default set to `FALSE`, so that nothing will be overwritten when the document is compiled. Of course unless you set `resetStyleFiles: TRUE` in the yaml header, respectively.

Let me know if this worked for you.
