### ISSUE TITLE
Change the Language of "Contents" and "Page Number"

### ISSUE THREAD

**Issue by canholyavkin** [INWTlab/ireports#6]
I am planning to use this package to generate reports in a non-English language. However, I couldn't change the "Contents" title and page counts (Page 1/2). How can I translate them?

**Comment by steffenWagner** [comment]
Hi Can,

thanks for your feedback. The solution is as follows. You need to change the some of the latex commands:

1. Translation of **Contents**:
   - This can be achieved by adding the last two lines to your YAML header of the markdown file. Now the "Contents" title will be the german 'Inhaltsverzeichnis':

```Rmd
---
title: Document Title
author: INWTlab 
date: \today
lang: ngerman
params:
  logo: logo.png
  cover: cover.png
  iblue: 2b4894
  igray: d4dbde
documentclass: article
fontsize: 10
papersize: a4paper
output: 
  IReports::businessReport:
    keep_tex: TRUE
    latex_engine: xelatex
    resetStyleFiles: FALSE
header-includes: 
  - \newcommand{\logo}{`r gsub("_", "\\_", params$logo)`}
  - \newcommand{\cover}{`r gsub("_", "\\_", params$cover)`}
  - \newcommand{\iblue}{`r params$iblue`}
  - \newcommand{\igray}{`r params$igray`}
include-before:
  - \renewcommand{\contentsname}{Inhaltsverzeichnis}
---
```
  - Please be aware that the identical change has to be made to the following line in the Rmd file.
```Rmd
\addcontentsline{toc}{section}{Inhaltsverzeichnis}
```

2. Translation of **Page**:
   - Since the usage of **Page**  is currently hard coded in the file `defs.tex` the following changes are required by your side:
    - Open `defs.tex` in a text editor and change line 102 from

```tex
\rfoot{Page \thepage \hspace{1pt} / \pageref{LastPage}}
```

for example to

```tex
\rfoot{Seite \thepage \hspace{1pt} / \pageref{LastPage}}
```
